### ISSUE TITLE
Modernize Python packaging with uv and latest dependencies

### ISSUE THREAD

**Issue by theshashank1** [theshashank1/TESH-Query#4]
Based on our conversation, here is a proposal to update the project with the latest dependency versions and proper uv support.

## Updated pyproject.toml with Latest Dependencies and uv Support

```toml
[build-system]
requires = [
    "setuptools>=75.0",
    "setuptools-scm>=8.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "teshq"
version = "1.3.2"
description = "A CLI tool that converts natural language queries into SQL and returns relevant tables using natural language."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
keywords = ["sql", "cli", "database", "natural language", "AI", "LLM"]
authors = [
  { name = "Shashank", email = "shashankgundas1@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "SQLAlchemy>=2.0.41",
    "python-dotenv>=1.0.1",
    "psycopg2-binary>=2.9.10",
    "langchain>=0.3.30",
    "langchain-core>=0.3.70",
    "langchain-google-genai>=2.2.0",
    "typer[all]>=0.15.10",
    "rich>=14.0.0",
    "logfire>=4.0.0",
    "tabulate>=0.9.0",
    "pandas>=2.2.3",
    "openpyxl>=3.1.5",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.7",
    "autopep8>=2.3.5",
    "pre-commit>=4.2.0",
    "flake8>=6.1.0",
    "isort>=5.13.2",
    "build>=1.2.0",
    "mkdocs-material>=9.5.40",
]

[project.urls]
Homepage = "https://github.com/theshashank1/TESH-Query"
"Bug Tracker" = "https://github.com/theshashank1/TESH-Query/issues"
Repository = "https://github.com/theshashank1/TESH-Query.git"
Documentation = "https://github.com/theshashank1/TESH-Query#readme"

[project.scripts]
teshq = "main:app"

[tool.setuptools]
packages = ["teshq", "teshq.cli", "teshq.cli.commands", "teshq.cli.ui", "teshq.core", "teshq.eda", "teshq.utils"]

# UV-specific configuration
[tool.uv]
dev-dependencies = [
    "pytest>=8.3.7",
    "autopep8>=2.3.5",
    "pre-commit>=4.2.0",
    "flake8>=6.1.0",
    "isort>=5.13.2",
    "build>=1.2.0",
    "mkdocs-material>=9.5.40",
]

# UV workspace configuration
[tool.uv.workspace]
members = []

# UV sources for dependency resolution
[tool.uv.sources]
# Use PyPI for all dependencies by default

# UV build configuration
[tool.uv.build]
include = ["teshq/", "README.md", "LICENSE"]
exclude = ["tests/", "docs/", "*.egg-info/"]
```

## Updated GitHub Actions Workflow

```yaml
name: Build and Publish TESH Query

on:
  push:
    tags:
      - 'v*'  # Only runs on annotated tags like v1.2.3
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    environment:
      name: pypi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync --dev

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest

      - name: Build package
        run: uv build

      - name: Check build output
        run: |
          ls -la dist/
          uv run python -m setuptools_scm

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
```

## Updated Requirements.txt (for pip compatibility)

```txt
# Core Application Dependencies
SQLAlchemy>=2.0.41
python-dotenv>=1.0.1
psycopg2-binary>=2.9.10
langchain>=0.3.30
langchain-core>=0.3.70
langchain-google-genai>=2.2.0
typer[all]>=0.15.10
rich>=14.0.0
logfire>=4.0.0
tabulate>=0.9.0

# Data Export
pandas>=2.2.3
openpyxl>=3.1.5

# Development Tools (optional)
pytest>=8.3.7
autopep8>=2.3.5
pre-commit>=4.2.0
flake8>=6.1.0
isort>=5.13.2
build>=1.2.0
mkdocs-material>=9.5.40
```

## Updated README Installation Section

This section should replace the existing installation guide in `README.md`.

````markdown
## Installation

### 🚀 Using uv (Recommended - Fastest)
```bash
# Install uv if you haven't already
curl -LsSf https://astral.sh/uv/install.sh | sh

# Install teshq globally
uv tool install teshq

# Or add to your project
uv add teshq
```

### 📦 Using pip (Traditional)
```bash
pip install teshq
```

### 🔧 Development Installation

#### Using uv (Recommended)
```bash
# Clone the repository
git clone https://github.com/theshashank1/TESH-Query.git
cd TESH-Query

# Install dependencies with uv
uv sync --dev

# Run the application
uv run teshq --help

# Run tests
uv run pytest

# Run linting
uv run pre-commit run --all-files
```

#### Using pip
```bash
# Clone the repository
git clone https://github.com/theshashank1/TESH-Query.git
cd TESH-Query

# Install in development mode
pip install -e ".[dev]"
```

### Performance Comparison
- **uv**: ~2-5 seconds for full dependency installation
- **pip**: ~30-60 seconds for full dependency installation

uv is 10-100x faster than pip for dependency resolution and installation!
